name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/727705881183/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'github-actions@kvm-nested-virtulization.iam.gserviceaccount.com'

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: index.html
          destination: gs://cs1660proj5
          parent: false
